version: "3.8"

services:
  frontend:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  auth-service:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
    restart: unless-stopped

  item-service:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
    restart: unless-stopped

  ai-service:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: unless-stopped

  user-service:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
    restart: unless-stopped

  transaction-service:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
    restart: unless-stopped

  postgres:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - POSTGRES_MAX_CONNECTIONS=200
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=768MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
    restart: unless-stopped

  redis:
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 384M
    restart: unless-stopped

  minio:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: unless-stopped
    environment:
      - MINIO_BROWSER_REDIRECT_URL=https://console.yourdomain.com
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    command: server /data --console-address ":9001" --address ":9000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - frontend
      - auth-service
      - item-service
      - user-service
      - transaction-service
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    restart: unless-stopped
